<?php
/* Copyright (C) 2013-2017  Christian Huke, Stephan Kreutzer
 *
 * This file is part of AutoMailer by refugee-it.de.
 *
 * AutoMailer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License version 3 or any later version,
 * as published by the Free Software Foundation.
 *
 * AutoMailer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License 3 for more details.
 *
 * You should have received a copy of the GNU Affero General Public License 3
 * along with AutoMailer. If not, see <http://www.gnu.org/licenses/>.
 */
/**
 * @file $/install.php
 * @brief Installation routine to set up the system.
 * @author Christian Huke, Stephan Kreutzer
 * @since 2013-09-13
 */



echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n".
     "<!DOCTYPE html\n".
     "    PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n".
     "    \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n".
     "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n".
     "  <head>\n".
     "    <meta http-equiv=\"content-type\" content=\"application/xhtml+xml; charset=UTF-8\"/>\n".
     "    <title>AutoMailer</title>\n".
     "  </head>\n".
     "  <body>\n";


$step = 1;

if (isset($_POST['step']) === true)
{
    if (is_numeric($_POST['step']) === true)
    {
        $step = (int)$_POST['step'];

/*
        if ($step == 3 &&
            isset($_POST['retry']) === true)
        {
            // Special handling for step 2 (retry other database connection
            // settings after one connection was already established successfully).
            $step = 2;
        }
*/

        if ($step == 4 &&
            isset($_POST['init']) === true)
        {
            // Special handling for step 3 (redo database initialization after
            // initialization was already completed successfully).
            $step = 3;
        }
        else if ($step == 5 &&
                 isset($_POST['save']) === true)
        {
            // Special handling for step 4 (redo save of the configuration after
            // saving was already completed successfully).
            $step = 4;
        }
    }
}

if (isset($_GET['stepjump']) === true)
{
    if (is_numeric($_GET['stepjump']) === true)
    {
        $step = (int)$_GET['stepjump'];
    }
}


if ($step == 1)
{
    echo "    <div>\n".
         "      <div>\n";

    require_once("license.inc.php");
    echo getHTMLLicenseNotification("license");
    echo "<hr/>\n";
    echo getHTMLLicenseFull("license");

    echo "      </div>\n".
         "      <div>\n".
         "        <form action=\"install.php\" method=\"post\">\n".
         "          <fieldset>\n".
         "            <input type=\"hidden\" name=\"step\" value=\"2\"/>\n".
         "            <input type=\"submit\" value=\"Continue\"/>\n".
         "          </fieldset>\n".
         "        </form>\n".
         "      </div>\n".
         "    </div>\n";
}
else if ($step == 2)
{
    $host = "localhost";
    $username = "root";
    $password = "";
    $database = "automailer";
    $prefix = "";

    if (isset($_POST['host']) === true)
    {
        $host = $_POST['host'];
    }

    if (isset($_POST['username']) === true)
    {
        $username = $_POST['username'];
    }

    if (isset($_POST['password']) === true)
    {
        $password = $_POST['password'];
    }

    if (isset($_POST['database']) === true)
    {
        $database = $_POST['database'];
    }

    if (isset($_POST['prefix']) === true)
    {
        $prefix = $_POST['prefix'];
    }

    echo "    <div>\n";

    if (file_exists("libraries/database_connect.inc.php") !== true)
    {
        $file = @fopen("libraries/database_connect.inc.php", "w");

        if ($file != false)
        {
            @fclose($file);
        }
        else
        {
            echo "      <p>\n".
                 "        Failed to create database_connect file.\n".
                 "      </p>\n";
        }
    }

    if (is_writable("libraries/database_connect.inc.php") === true)
    {
        /**
         * @todo Make sure that strings in $host, $database, ... don't contain characters
         *     that break PHP or SQL.
         */

        $php_code = "<?php\n".
                    "// This file was automatically generated by the installation routine.\n".
                    "\n".
                    "\$pdo = false;\n".
                    "\$db_table_prefix = \"$prefix\"; // Prefix for database tables.\n".
                    "\$exceptionConnectFailure = NULL;\n".
                    "\n".
                    "\n".
                    "try\n".
                    "{\n".
                    "    \$pdo = @new PDO('mysql:host=".$host.";dbname=".$database.";charset=utf8', \"".$username."\", \"".$password."\");\n".
                    "}\n".
                    "catch (PDOException \$ex)\n".
                    "{\n".
                    "    \$pdo = false;\n".
                    "    \$exceptionConnectFailure = \$ex;\n".
                    "}\n".
                    "\n".
                    "?>\n";

        $file = @fopen("libraries/database_connect.inc.php", "wb");

        if ($file != false)
        {
            if (@fwrite($file, $php_code) == false)
            {
                echo "      <p>\n".
                     "        Failed to write database_connect file.\n".
                     "      </p>\n";
            }

            @fclose($file);
        }
        else
        {
            echo "      <p>\n".
                 "        Failed to open database_connect file for writing.\n".
                 "      </p>\n";
        }
    }
    else
    {
        echo "      <p>\n".
             "        database_connect file isn't writable.\n".
             "      </p>\n";
    }


    $successConnect = false;

    clearstatcache();

    if (file_exists("libraries/database_connect.inc.php") === true)
    {
        if (is_readable("libraries/database_connect.inc.php") === true)
        {
            require_once("libraries/database.inc.php");

            if (Database::Get()->IsConnected() === true)
            {
                $successConnect = true;
            }
            else
            {
                if (strlen(Database::Get()->GetLastErrorMessage()) > 0)
                {
                    echo "      <p>\n".
                         "        Failed to connect to database: ".htmlspecialchars(Database::Get()->GetLastErrorMessage(), ENT_COMPAT | ENT_HTML401, "UTF-8")."\n".
                         "      </p>\n";
                }
                else
                {
                    echo "      <p>\n".
                         "        Failed to connect to database.\n".
                         "      </p>\n";
                }
            }
        }
        else
        {
            echo "      <p>\n".
                 "        database_connect file isn't readable.\n".
                 "      </p>\n";
        }
    }
    else
    {
        echo "      <p>\n".
             "        database_connect file doesn't exist.\n".
             "      </p>\n";
    }

    if (isset($_POST['save']) == false ||
        $successConnect == false)
    {
        echo "      <div>\n".
             "        <form action=\"install.php\" method=\"post\">\n".
             "          <fieldset>\n".
             "            <input type=\"hidden\" name=\"step\" value=\"2\"/>\n".
             "            <input type=\"text\" name=\"host\" value=\"".htmlspecialchars($host, ENT_COMPAT | ENT_HTML401, "UTF-8")."\"/> Host<br/>\n".
             "            <input type=\"text\" name=\"username\" value=\"".htmlspecialchars($username, ENT_COMPAT | ENT_HTML401, "UTF-8")."\"/> User name<br/>\n".
             "            <input type=\"password\" name=\"password\" value=\"".htmlspecialchars($password, ENT_COMPAT | ENT_HTML401, "UTF-8")."\"/> Password<br/>\n".
             "            <input type=\"text\" name=\"database\" value=\"".htmlspecialchars($database, ENT_COMPAT | ENT_HTML401, "UTF-8")."\"/> Database name<br/>\n".
             "            <input type=\"text\" name=\"prefix\" value=\"".htmlspecialchars($prefix, ENT_COMPAT | ENT_HTML401, "UTF-8")."\"/> Table prefix<br/>\n".
             "            <input type=\"submit\" name=\"save\" value=\"Save\"/>\n".
             "          </fieldset>\n".
             "        </form>\n".
             "      </div>\n";
    }
    else
    {
        echo "      <div>\n".
             "        <fieldset>\n".
             "          <form action=\"install.php\" method=\"post\">\n".
             "            <input type=\"hidden\" name=\"step\" value=\"2\"/>\n".
             "            <input type=\"hidden\" name=\"host\" value=\"".htmlspecialchars($host, ENT_COMPAT | ENT_HTML401, "UTF-8")."\"/>\n".
             "            <input type=\"hidden\" name=\"username\" value=\"".htmlspecialchars($username, ENT_COMPAT | ENT_HTML401, "UTF-8")."\"/>\n".
             "            <input type=\"hidden\" name=\"password\" value=\"".htmlspecialchars($password, ENT_COMPAT | ENT_HTML401, "UTF-8")."\"/>\n".
             "            <input type=\"hidden\" name=\"database\" value=\"".htmlspecialchars($database, ENT_COMPAT | ENT_HTML401, "UTF-8")."\"/>\n".
             "            <input type=\"hidden\" name=\"prefix\" value=\"".htmlspecialchars($prefix, ENT_COMPAT | ENT_HTML401, "UTF-8")."\"/>\n".
             "            <input type=\"submit\" value=\"Change\"/>\n".
             "          </fieldset>\n".
             "        </form>\n".
             "      </div>\n".
             "      <div>\n".
             "        <form action=\"install.php\" method=\"post\">\n".
             "          <fieldset>\n".
             "            <input type=\"hidden\" name=\"step\" value=\"3\"/>\n".
             "            <input type=\"submit\" value=\"Continue\"/>\n".
             "          </fieldset>\n".
             "        </form>\n".
             "      </div>\n";
    }

    echo "    </div>\n";
}
else if ($step == 3)
{
    $dropExistingTables = false;
    $keepExistingTables = false;

    if (isset($_POST['drop_existing_tables']) === true)
    {
        $dropExistingTables = true;
    }

    if (isset($_POST['keep_existing_tables']) === true)
    {
        $keepExistingTables = true;
    }


    echo "    <div>\n";


    $successInit = false;

    if (isset($_POST['init']) === true)
    {
        require_once("libraries/database.inc.php");

        if (Database::Get()->IsConnected() === true)
        {
            $success = Database::Get()->BeginTransaction();

            // Table users

            if ($success === true)
            {
                if ($dropExistingTables === true)
                {
                    if (Database::Get()->ExecuteUnsecure("DROP TABLE IF EXISTS `".Database::Get()->GetPrefix()."users`") !== true)
                    {
                        $success = false;
                    }
                }
            }

            if ($success === true)
            {
                $sql = "CREATE TABLE ";

                if ($keepExistingTables === true)
                {
                    $sql .= "IF NOT EXISTS ";
                }

                $sql .= "`".Database::Get()->GetPrefix()."users` (".
                        "  `id` int(11) NOT NULL AUTO_INCREMENT,".
                        "  `name` varchar(40) COLLATE utf8_bin NOT NULL,".
                        "  `salt` varchar(255) COLLATE utf8_bin NOT NULL,".
                        "  `password` varchar(255) COLLATE utf8_bin NOT NULL,".
                        "  PRIMARY KEY (`id`),".
                        "  UNIQUE KEY `name` (`name`)".
                        ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin";

                if (Database::Get()->ExecuteUnsecure($sql) !== true)
                {
                    $success = false;
                }
            }

            // Table addressees

            if ($success === true)
            {
                if ($dropExistingTables === true)
                {
                    if (Database::Get()->ExecuteUnsecure("DROP TABLE IF EXISTS `".Database::Get()->GetPrefix()."addressees`") !== true)
                    {
                        $success = false;
                    }
                }
            }

            if ($success === true)
            {
                $sql = "CREATE TABLE ";

                if ($keepExistingTables === true)
                {
                    $sql .= "IF NOT EXISTS ";
                }

                $sql .= "`".Database::Get()->GetPrefix()."addressees` (".
                        "  `id` int(11) NOT NULL AUTO_INCREMENT,".
                        "  `family_name` varchar(255) COLLATE utf8_bin NOT NULL,".
                        "  `given_name` varchar(255) COLLATE utf8_bin,".
                        "  `gender` int(11) NOT NULL,".
                        "  `e_mail` varchar(255) COLLATE utf8_bin NOT NULL,".
                        "  `sent` datetime,".
                        "  PRIMARY KEY (`id`),".
                        "  UNIQUE KEY `e_mail` (`e_mail`)".
                        ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin";

                if (Database::Get()->ExecuteUnsecure($sql) !== true)
                {
                    $success = false;
                }
            }


            if ($success === true)
            {
                if (Database::Get()->commitTransaction() === true)
                {
                    $successInit = true;
                }
                else
                {
                    echo "      <p>\n".
                         "        Database commit failed.\n".
                         "      </p>\n";
                }
            }
            else
            {
                if (strlen(Database::Get()->GetLastErrorMessage()) > 0)
                {
                    echo "      <p>\n".
                         "        Database operation failed: ".htmlspecialchars(Database::Get()->GetLastErrorMessage(), ENT_COMPAT | ENT_HTML401, "UTF-8")."\n".
                         "      </p>\n";
                }
                else
                {
                    echo "      <p>\n".
                         "        Database operation failed.\n".
                         "      </p>\n";
                }

                Database::Get()->RollbackTransaction();
            }
        }
        else
        {
            if (strlen(Database::Get()->GetLastErrorMessage()) > 0)
            {
                echo "      <p>\n".
                     "        Database connect failed: ".htmlspecialchars(Database::Get()->GetLastErrorMessage(), ENT_COMPAT | ENT_HTML401, "UTF-8")."\n".
                     "      </p>\n";
            }
            else
            {
                echo "      <p>\n".
                     "        Database connect failed.\n".
                     "      </p>\n";
            }
        }
    }

    echo "      <div>\n".
         "        <form action=\"install.php\" method=\"post\">\n".
         "          <fieldset>\n";

    if ($successInit === true)
    {
        echo "            <input type=\"hidden\" name=\"step\" value=\"4\"/>\n";
    }
    else
    {
        echo "            <input type=\"hidden\" name=\"step\" value=\"3\"/>\n";
    }

    if ($dropExistingTables === true)
    {
        echo "            <input type=\"checkbox\" name=\"drop_existing_tables\" value=\"drop\" checked=\"checked\"/> Drop existing tables.<br/>\n";
    }
    else
    {
        echo "            <input type=\"checkbox\" name=\"drop_existing_tables\" value=\"drop\"/> Drop existing tables.<br/>\n";
    }

    if ($keepExistingTables === true)
    {
        echo "            <input type=\"checkbox\" name=\"keep_existing_tables\" value=\"keep\" checked=\"checked\"/> Keep existing tables.<br/>\n";
    }
    else
    {
        echo "            <input type=\"checkbox\" name=\"keep_existing_tables\" value=\"keep\"/> Keep existing tables.<br/>\n";
    }

    echo "            <input type=\"submit\" name=\"init\" value=\"Initialize\"/>\n";

    if ($successInit === true)
    {
        echo "            <input type=\"submit\" value=\"Continue\"/>\n";
    }

    echo "          </fieldset>\n".
         "        </form>\n".
         "      </div>\n".
         "    </div>\n";
}
else if ($step == 4)
{
    $userName = "";
    $userPassword = "";

    if (isset($_POST['username']) === true)
    {
        $userName = $_POST['username'];
    }

    if (isset($_POST['password']) === true)
    {
        $userPassword = $_POST['password'];
    }

    echo "    <div>\n";

    $successDelete = false;
    $successCreate = false;

    if (isset($_POST['save']) === true &&
        !empty($userName) &&
        !empty($userPassword))
    {
        require_once("libraries/database.inc.php");
        
        if (Database::Get()->IsConnected() === true)
        {
            $successDelete = Database::Get()->ExecuteUnsecure("DELETE FROM `".Database::Get()->GetPrefix()."users` WHERE 1");
        }

        if ($successDelete === true)
        {
            $salt = md5(uniqid(rand(), true));
            $userPassword = hash('sha512', $salt.$userPassword);

            $id = Database::Get()->Insert("INSERT INTO `".Database::Get()->GetPrefix()."users` (`id`,\n".
                                          "    `name`,\n".
                                          "    `salt`,\n".
                                          "    `password`)\n".
                                          "VALUES (?, ?, ?, ?)\n",
                                          array(NULL, $userName, $salt, $userPassword),
                                          array(Database::TYPE_NULL, Database::TYPE_STRING, Database::TYPE_STRING, Database::TYPE_STRING));

            if ($id > 0)
            {
                $user = array("id" => $id);
                $successCreate = true;
            }
        }

        if ($successDelete != true ||
            $successCreate != true)
        {
            echo "      <p>\n".
                 "        Database operation failed.\n".
                 "      </p>\n".
                 "    </div>\n".
                 "  </body>\n".
                 "</html>\n";

            exit(-1);
        }
    }

    echo "      <div>\n".
         "        <form action=\"install.php\" method=\"post\">\n".
         "          <fieldset>\n".
         "            <input type=\"hidden\" name=\"step\" value=\"5\"/>\n".
         "            <input type=\"text\" name=\"username\" value=\"".htmlspecialchars($userName, ENT_COMPAT | ENT_HTML401, "UTF-8")."\" size=\"20\" maxlength=\"60\"//> User name<br/>\n".
         "            <input type=\"password\" name=\"password\" value=\"\" size=\"20\" maxlength=\"60\"/> Password<br/>\n".
         "            <input type=\"submit\" name=\"save\" value=\"Save\"/>\n";

    if ($successCreate === true)
    {
        echo "          <input type=\"submit\" value=\"Continue\"/>\n";
    }

    echo "          </fieldset>\n".
         "        </form>\n".
         "      </div>\n".
         "    </div>\n";
}
else if ($step == 5)
{
    if (@unlink(__FILE__) === true)
    {
        clearstatcache();

        echo "    <div>\n".
             "      <a href=\"index.php\">Done</a>\n".
             "    </div>\n";
    }
    else
    {
        echo "    <div>\n".
             "      <p>\n".
             "        Automatic deletion of the install script failed. Please delete it manually!\n".
             "      </p>\n".
             "    </div>\n";
    }
}

echo "  </body>\n".
     "</html>\n";



?>
